youtube:
    resource: "@AcmeYoutubeSearchBundle/Controller/DefaultController.php"
    type:     annotation
clip:
    resource: "@AcmeYoutubeSearchBundle/Controller/ClipController.php"
    type:     annotation
tag:
    resource: "@AcmeYoutubeSearchBundle/Controller/TagController.php"
    type:     annotation