parameters:
#    acme_youtube_search.example.class: Acme\YoutubeSearchBundle\Example

services:
#    acme_youtube_search.example:
#        class: %acme_youtube_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
